In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#pandas

In [3]:
#install pandas

In [4]:
import pandas as pd

In [9]:
s=pd.Series([10,20,30])

In [10]:
s

0    10
1    20
2    30
dtype: int64

In [14]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [15]:
s

a    10
b    20
c    30
dtype: int64

In [16]:
#dic

In [18]:
dic={
    "name":"Tanishka",
    "age":17,
    "marks":75
}

In [19]:
dic

{'name': 'Tanishka', 'age': 17, 'marks': 75}

In [22]:
s=pd.Series(dic)

In [23]:
s

name     Tanishka
age            17
marks          75
dtype: object

In [27]:
pd.Series(5,index=['0','1','2','3','4'])

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [30]:
s1=pd.Series([10,20,30],index=['a','b','c'])

#

In [31]:
s1

a    10
b    20
c    30
dtype: int64

In [32]:
s1.values

array([10, 20, 30])

In [33]:
s1.index

Index(['a', 'b', 'c'], dtype='object')

In [35]:
s1.dtype

dtype('int64')

In [36]:
s1.shape

(3,)

In [37]:
s1*2

a    20
b    40
c    60
dtype: int64

In [44]:
s1=pd.Series([10,None,30])

In [45]:
s1

0    10.0
1     NaN
2    30.0
dtype: float64

In [47]:
s1.isnull()

0    False
1     True
2    False
dtype: bool

In [50]:
s1.dropna()

0    10.0
2    30.0
dtype: float64

In [51]:
s1.fillna(20)

0    10.0
1    20.0
2    30.0
dtype: float64

In [52]:
s1=pd.Series([1,2,2,3,3,3])

In [53]:
s1

0    1
1    2
2    2
3    3
4    3
5    3
dtype: int64

In [55]:
s1.value_counts()

3    3
2    2
1    1
Name: count, dtype: int64

In [57]:
s=pd.Series([10,20,30,40],index=['a','b','c','d'])

In [58]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [60]:
s['a']

np.int64(10)

In [61]:
s['b']

np.int64(20)

In [62]:
s['c']

np.int64(30)

In [63]:
s['d']

np.int64(40)

In [64]:
#create data frame(2D)

In [78]:
s=pd.DataFrame({
    "name":["Tanishka","Sayali"],
    "age":[17,16]
})

In [79]:
s

       name  age
0  Tanishka   17
1    Sayali   16

In [86]:
data={
    "roll_no":[100,200,300,400],
    "name":["omkar","shrwan","sayali","rahul"],
    "marks":[99,100,101,None]
}

In [87]:
data

{'roll_no': [100, 200, 300, 400],
 'name': ['omkar', 'shrwan', 'sayali', 'rahul'],
 'marks': [99, 100, 101, None]}

In [88]:
df=pd.DataFrame(data)

In [89]:
df

   roll_no    name  marks
0      100   omkar   99.0
1      200  shrwan  100.0
2      300  sayali  101.0
3      400   rahul    NaN

In [91]:
d={
    "subject":["java","python","css"],
    "marks":[99,100,101],
    "grade":['A','B','C']
}

In [92]:
d

{'subject': ['java', 'python', 'css'],
 'marks': [99, 100, 101],
 'grade': ['A', 'B', 'C']}

In [93]:
df=pd.DataFrame(d)

In [94]:
df

  subject  marks grade
0    java     99     A
1  python    100     B
2     css    101     C

In [101]:
df.to_csv('marks_data.csv',index=False)

In [105]:
df=pd.read_csv('marks_data.csv')

In [106]:
df

  subject  marks grade
0    java     99     A
1  python    100     B
2     css    101     C

In [107]:
df.head()

  subject  marks grade
0    java     99     A
1  python    100     B
2     css    101     C

In [109]:
df.tail()

  subject  marks grade
0    java     99     A
1  python    100     B
2     css    101     C

In [111]:
df.shape

(3, 3)

In [117]:
df.columns

Index(['subject', 'marks', 'grade'], dtype='object')

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subject  3 non-null      object
 1   marks    3 non-null      int64
 2   grade    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [119]:
df.describe()

       marks
count    3.0
mean   100.0
std      1.0
min     99.0
25%     99.5
50%    100.0
75%    100.5
max    101.0

In [125]:
df.isnull().sum

<bound method DataFrame.sum of    subject  marks  grade
0    False  False  False
1    False  False  False
2    False  False  False>

In [127]:
df=df.drop_duplicates()

In [128]:
df

  subject  marks grade
0    java     99     A
1  python    100     B
2     css    101     C

In [129]:
df['marks']=df['marks'].astype(float)

In [130]:
df

  subject  marks grade
0    java   99.0     A
1  python  100.0     B
2     css  101.0     C

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subject  3 non-null      object
 1   marks    3 non-null      float64
 2   grade    3 non-null      object
dtypes: float64(1), object(2)
memory usage: 204.0+ bytes

In [134]:
df["subject"]

0      java
1    python
2       css
Name: subject, dtype: object

In [140]:
df[["subject","marks"]]

  subject  marks
0    java   99.0
1  python  100.0
2     css  101.0

In [141]:
df=df.sort_values(by="marks",ascending=False)

In [142]:
df

  subject  marks grade
2     css  101.0     C
1  python  100.0     B
0    java   99.0     A